# NumPy Array Muscle Memory Drills

This is a NumPy-only practice ladder for building fast array intuition.

How to use it:
- Run the setup cell once.
- In each challenge cell, replace `None` with one NumPy expression.
- Run the cell. `correct` means move on.
- If it is not correct, inspect the shape first.

The early cells should be 15-30 second reflexes. The final cells are closer to competition-style shape reasoning.


In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
rng = np.random.default_rng(42)

# Shared arrays for the drills. Do not mutate these unless a challenge asks for a copy.
a = np.array([3, -1, 0, 7, -4, 2])
b = np.arange(12)
M = np.arange(1, 13).reshape(3, 4)
N = np.array([[2, -1, 5], [0, 3, -2], [4, 4, 1], [-3, 2, 6]])
scores = np.array([55, 72, 91, 48, 88, 64, 79, 35, 100, 67])
labels = np.array(["cat", "dog", "cat", "bird", "dog", "cat"])
X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [2.0, 4.0, 8.0],
])
Y = np.array([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])
image = np.arange(4 * 5 * 3).reshape(4, 5, 3)
grades = np.array([
    [8, 7, 9, 6],
    [5, 6, 6, 7],
    [10, 9, 8, 10],
    [4, 5, 6, 5],
    [7, 8, 7, 9],
])
tiny = np.array([[0, 2, 0], [3, 0, 4], [0, 5, 6]])
walk = np.array([2, -1, 3, -2, 4, -3])


def _same(got, expected):
    if isinstance(expected, np.ndarray):
        if not isinstance(got, np.ndarray) or got.shape != expected.shape:
            return False
        if expected.dtype.kind in "OUS":
            return np.array_equal(got, expected)
        return np.allclose(got, expected)
    if isinstance(expected, tuple):
        return isinstance(got, tuple) and len(got) == len(expected) and all(_same(g, e) for g, e in zip(got, expected))
    if isinstance(expected, list):
        return isinstance(got, list) and len(got) == len(expected) and all(_same(g, e) for g, e in zip(got, expected))
    if isinstance(expected, (float, np.floating)):
        return np.allclose(got, expected)
    return got == expected


def check(challenge_id, answer):
    expected = EXPECTED[challenge_id]
    if answer is None:
        print(f"{challenge_id}: not solved yet")
        return
    ok = _same(answer, expected)
    if ok:
        print(f"{challenge_id}: correct")
    else:
        print(f"{challenge_id}: not yet")
        print("got:", answer)
        if isinstance(answer, np.ndarray):
            print("got shape:", answer.shape)
        print("expected shape:", expected.shape if isinstance(expected, np.ndarray) else type(expected).__name__)


EXPECTED = {
    "c01": np.array([0, 1, 2, 3, 4]),
    "c02": np.arange(2, 21, 2),
    "c03": np.zeros((2, 3), dtype=int),
    "c04": np.full((3, 2), 7),
    "c05": np.linspace(0, 1, 5),
    "c06": (M.shape, M.ndim, M.size),
    "c07": a.astype(float),
    "c08": b.reshape(3, 4),
    "c09": M.ravel(),
    "c10": M[:, 0],
    "c11": M[-1],
    "c12": M[:2, 1:3],
    "c13": M[:, ::2],
    "c14": M[::-1],
    "c15": a[a > 0],
    "c16": np.where(scores >= 70)[0],
    "c17": np.where(a < 0, 0, a),
    "c18": np.array([5, 3, 1]),
    "c19": N[[0, 2, 3], [2, 0, 1]],
    "c20": M + np.array([10, 20, 30, 40]),
    "c21": M * np.array([[1], [10], [100]]),
    "c22": N.mean(axis=0),
    "c23": grades.mean(axis=1),
    "c24": grades.max(axis=0),
    "c25": np.count_nonzero(tiny, axis=1),
    "c26": np.unique(labels),
    "c27": np.unique(labels, return_counts=True),
    "c28": np.sort(scores),
    "c29": scores[np.argsort(scores)[-3:]],
    "c30": M.T,
    "c31": X @ np.array([0.2, 0.3, 0.5]),
    "c32": X @ Y,
    "c33": np.linalg.norm(X, axis=1),
    "c34": X - X.mean(axis=0, keepdims=True),
    "c35": X / np.linalg.norm(X, axis=1, keepdims=True),
    "c36": (scores - scores.mean()) / scores.std(),
    "c37": np.concatenate([M, M], axis=0),
    "c38": np.concatenate([M, M], axis=1),
    "c39": np.stack([a, -a], axis=0),
    "c40": image[:, :, 0],
    "c41": image[1:3, 2:5, :],
    "c42": image.mean(axis=(0, 1)),
    "c43": np.cumsum(walk),
    "c44": np.diff(scores),
    "c45": np.clip(scores, 50, 90),
    "c46": np.pad(a, (2, 1), constant_values=0),
    "c47": np.eye(4, dtype=int),
    "c48": np.diag(np.array([1, 2, 3])),
    "c49": ((X[:, None, :] - X[None, :, :]) ** 2).sum(axis=2),
    "c50": np.einsum("ij,jk->ik", X, Y),
}


## Drill Ladder

Do not write loops unless a challenge explicitly asks for one. The point is to make array creation, slicing, broadcasting, and reductions automatic.


In [2]:
# Challenge 01 - creation (15 sec)
# Task: Create np.array([0, 1, 2, 3, 4]).
answer = np.array([0, 1, 2, 3,4])

check("c01", answer)


c01: correct


In [6]:
# Challenge 02 - arange (15 sec)
# Task: Create the even numbers from 2 through 20.
answer = np.array(range(2, 22, 2))

check("c02", answer)


c02: correct


In [7]:
# Challenge 03 - zeros and shape (15 sec)
# Task: Create a 2 by 3 integer array of zeros.
answer = np.zeros((2,3))

check("c03", answer)


c03: correct


In [10]:
# Challenge 04 - full (15 sec)
# Task: Create a 3 by 2 array filled with 7.
answer = np.array(7)

check("c04", answer)


c04: not yet
got: 7
got shape: ()
expected shape: (3, 2)


In [11]:
# Challenge 05 - linspace (20 sec)
# Task: Create 5 equally spaced values from 0 to 1.
answer = np.linspace(0, 1, 5)

check("c05", answer)


c05: correct


In [12]:
# Challenge 06 - shape attributes (20 sec)
# Task: Return a tuple with M's shape, number of dimensions, and total size.
answer = M.shape, M.ndim, M.size

check("c06", answer)


c06: correct


In [13]:
# Challenge 07 - astype (20 sec)
# Task: Convert a to floating point dtype.
answer = np.astype(a, np.float32)

check("c07", answer)


c07: correct


In [14]:
# Challenge 08 - reshape (20 sec)
# Task: Reshape b into a 3 by 4 matrix.
answer = b.reshape(3, 4)

check("c08", answer)


c08: correct


In [15]:
# Challenge 09 - ravel (20 sec)
# Task: Flatten M into one dimension.
answer = M.flatten()

check("c09", answer)


c09: correct


In [17]:
# Challenge 10 - column indexing (20 sec)
# Task: Select the first column of M.
answer = M[:,0]

check("c10", answer)


c10: correct


In [18]:
# Challenge 11 - negative indexing (20 sec)
# Task: Select the last row of M.
answer = M[-1]

check("c11", answer)


c11: correct


In [20]:
# Challenge 12 - 2D slicing (30 sec)
# Task: Select the first two rows and middle two columns of M.
answer = M[:2,M.shape[0]//2:(M.shape[0]//2)+2]

check("c12", answer)


c12: correct


In [22]:
# Challenge 13 - step slicing (30 sec)
# Task: Select every other column of M, starting from column 0.
answer = M[:,]

check("c13", answer)


c13: not yet
got: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
got shape: (3, 4)
expected shape: (3, 2)


In [ ]:
# Challenge 14 - reverse slicing (30 sec)
# Task: Reverse the row order of M.
answer = M

check("c14", answer)


c14: not yet
got: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
got shape: (3, 4)
expected shape: (3, 4)


In [25]:
# Challenge 15 - boolean mask (30 sec)
# Task: Return only the positive values in a.
answer = a[a>0]

check("c15", answer)


c15: correct


In [ ]:
# Challenge 16 - np.where indices (40 sec)
# Task: Return the indices where scores are at least 70.
answer = np.where(a>=70, a, a)

check("c16", answer)


c16: not yet
got: [None None None None None None]
got shape: (6,)
expected shape: (5,)


In [29]:
# Challenge 17 - np.where values (40 sec)
# Task: Replace negative values in a with 0, preserving shape.
answer = np.where(a>0, a, 0)

check("c17", answer)


c17: correct


In [30]:
# Challenge 18 - fancy indexing (40 sec)
# Task: From a, select positions [3, 0, 1] in that order.
answer = a

check("c18", answer)


c18: not yet
got: [ 3 -1  0  7 -4  2]
got shape: (6,)
expected shape: (3,)


In [31]:
# Challenge 19 - paired fancy indexing (45 sec)
# Task: From N, select values at (row, col): (0,2), (2,0), (3,1).
answer = N

check("c19", answer)


c19: not yet
got: [[ 2 -1  5]
 [ 0  3 -2]
 [ 4  4  1]
 [-3  2  6]]
got shape: (4, 3)
expected shape: (3,)


In [ ]:
# Challenge 20 - broadcast row vector (45 sec)
# Task: Add [10, 20, 30, 40] to every row of M.
answer = None

check("c20", answer)


In [ ]:
# Challenge 21 - broadcast column vector (45 sec)
# Task: Multiply M's rows by 1, 10, and 100 respectively.
answer = None

check("c21", answer)


In [ ]:
# Challenge 22 - axis 0 reduction (45 sec)
# Task: Compute the mean of each column in N.
answer = None

check("c22", answer)


In [ ]:
# Challenge 23 - axis 1 reduction (45 sec)
# Task: Compute the mean grade for each student.
answer = None

check("c23", answer)


In [ ]:
# Challenge 24 - max by column (45 sec)
# Task: Compute the best score for each exam/column in grades.
answer = None

check("c24", answer)


In [ ]:
# Challenge 25 - count_nonzero (45 sec)
# Task: Count nonzero entries in each row of tiny.
answer = None

check("c25", answer)


In [ ]:
# Challenge 26 - unique (45 sec)
# Task: Return the unique labels.
answer = None

check("c26", answer)


In [ ]:
# Challenge 27 - unique counts (60 sec)
# Task: Return unique labels and their counts.
answer = None

check("c27", answer)


In [ ]:
# Challenge 28 - sort (45 sec)
# Task: Return sorted scores in ascending order.
answer = None

check("c28", answer)


In [ ]:
# Challenge 29 - argsort (60 sec)
# Task: Return the top 3 scores using argsort. Ascending order is fine.
answer = None

check("c29", answer)


In [ ]:
# Challenge 30 - transpose (30 sec)
# Task: Transpose M.
answer = None

check("c30", answer)


In [ ]:
# Challenge 31 - matrix vector (60 sec)
# Task: Compute a weighted sum of X columns with weights [0.2, 0.3, 0.5].
answer = None

check("c31", answer)


In [ ]:
# Challenge 32 - matrix matrix (60 sec)
# Task: Compute the matrix product X @ Y.
answer = None

check("c32", answer)


In [ ]:
# Challenge 33 - row norm (60 sec)
# Task: Compute the L2 norm of each row in X.
answer = None

check("c33", answer)


In [ ]:
# Challenge 34 - keepdims broadcasting (75 sec)
# Task: Column-center X by subtracting each column mean.
answer = None

check("c34", answer)


In [ ]:
# Challenge 35 - row normalization (75 sec)
# Task: Normalize each row of X to unit length.
answer = None

check("c35", answer)


In [ ]:
# Challenge 36 - standardization (75 sec)
# Task: Standardize scores to mean 0 and standard deviation 1.
answer = None

check("c36", answer)


In [ ]:
# Challenge 37 - concatenate rows (60 sec)
# Task: Stack M under itself to make a 6 by 4 array.
answer = None

check("c37", answer)


In [ ]:
# Challenge 38 - concatenate columns (60 sec)
# Task: Place M next to itself to make a 3 by 8 array.
answer = None

check("c38", answer)


In [ ]:
# Challenge 39 - stack new axis (60 sec)
# Task: Stack a and -a into a 2 by 6 array.
answer = None

check("c39", answer)


In [ ]:
# Challenge 40 - 3D indexing (60 sec)
# Task: Select channel 0 from image.
answer = None

check("c40", answer)


In [ ]:
# Challenge 41 - 3D slicing (75 sec)
# Task: Crop rows 1:3 and columns 2:5 from image, keeping all channels.
answer = None

check("c41", answer)


In [ ]:
# Challenge 42 - multi-axis reduction (75 sec)
# Task: Compute the mean value per image channel.
answer = None

check("c42", answer)


In [ ]:
# Challenge 43 - cumsum (60 sec)
# Task: Compute the cumulative position after each step in walk.
answer = None

check("c43", answer)


In [ ]:
# Challenge 44 - diff (60 sec)
# Task: Compute consecutive score differences.
answer = None

check("c44", answer)


In [ ]:
# Challenge 45 - clip (60 sec)
# Task: Clip scores so every value is between 50 and 90.
answer = None

check("c45", answer)


In [ ]:
# Challenge 46 - pad (75 sec)
# Task: Pad a with two zeros on the left and one zero on the right.
answer = None

check("c46", answer)


In [ ]:
# Challenge 47 - eye (45 sec)
# Task: Create a 4 by 4 integer identity matrix.
answer = None

check("c47", answer)


In [ ]:
# Challenge 48 - diag (60 sec)
# Task: Create a diagonal matrix with diagonal [1, 2, 3].
answer = None

check("c48", answer)


In [ ]:
# Challenge 49 - broadcast pairwise distances (3 min)
# Task: Compute the full pairwise squared-distance matrix between rows of X.
answer = None

check("c49", answer)


In [ ]:
# Challenge 50 - einsum (3 min)
# Task: Recreate X @ Y using np.einsum.
answer = None

check("c50", answer)


## Stop Condition

You are done when:
- Challenges 01-20 feel automatic.
- For 21-40, you can predict the output shape before running the cell.
- For 41-50, you can debug a wrong answer by printing only shapes first.

Reusable contest reflex: shape first, values second.
