# NumPy Array Muscle Memory Drills

This is a NumPy-only practice ladder for building fast array intuition.

How to use it:
- Run the setup cell once.
- In each challenge cell, replace `None` with one NumPy expression.
- Run the cell. `correct` means move on.
- If it is not correct, inspect the shape first.

The early cells should be 15-30 second reflexes. The final cells are closer to competition-style shape reasoning.


In [129]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
rng = np.random.default_rng(42)

# Shared arrays for the drills. Do not mutate these unless a challenge asks for a copy.
a = np.array([3, -1, 0, 7, -4, 2])
b = np.arange(12)
M = np.arange(1, 13).reshape(3, 4)
N = np.array([[2, -1, 5], [0, 3, -2], [4, 4, 1], [-3, 2, 6]])
scores = np.array([55, 72, 91, 48, 88, 64, 79, 35, 100, 67])
labels = np.array(["cat", "dog", "cat", "bird", "dog", "cat"])
X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [2.0, 4.0, 8.0],
])
Y = np.array([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])
image = np.arange(4 * 5 * 3).reshape(4, 5, 3)
grades = np.array([
    [8, 7, 9, 6],
    [5, 6, 6, 7],
    [10, 9, 8, 10],
    [4, 5, 6, 5],
    [7, 8, 7, 9],
])
tiny = np.array([[0, 2, 0], [3, 0, 4], [0, 5, 6]])
walk = np.array([2, -1, 3, -2, 4, -3])


def _same(got, expected):
    if isinstance(expected, np.ndarray):
        if not isinstance(got, np.ndarray) or got.shape != expected.shape:
            return False
        if expected.dtype.kind in "OUS":
            return np.array_equal(got, expected)
        return np.allclose(got, expected)
    if isinstance(expected, tuple):
        return isinstance(got, tuple) and len(got) == len(expected) and all(_same(g, e) for g, e in zip(got, expected))
    if isinstance(expected, list):
        return isinstance(got, list) and len(got) == len(expected) and all(_same(g, e) for g, e in zip(got, expected))
    if isinstance(expected, (float, np.floating)):
        return np.allclose(got, expected)
    return got == expected


def check(challenge_id, answer):
    expected = EXPECTED[challenge_id]
    if answer is None:
        print(f"{challenge_id}: not solved yet")
        return
    ok = _same(answer, expected)
    if ok:
        print(f"{challenge_id}: correct")
    else:
        print(f"{challenge_id}: not yet")
        print("got:", answer)
        if isinstance(answer, np.ndarray):
            print("got shape:", answer.shape)
        print("expected shape:", expected.shape if isinstance(expected, np.ndarray) else type(expected).__name__)


EXPECTED = {
    "c01": np.array([0, 1, 2, 3, 4]),
    "c02": np.arange(2, 21, 2),
    "c03": np.zeros((2, 3), dtype=int),
    "c04": np.full((3, 2), 7),
    "c05": np.linspace(0, 1, 5),
    "c06": (M.shape, M.ndim, M.size),
    "c07": a.astype(float),
    "c08": b.reshape(3, 4),
    "c09": M.ravel(),
    "c10": M[:, 0],
    "c11": M[-1],
    "c12": M[:2, 1:3],
    "c13": M[:, ::2],
    "c14": M[::-1],
    "c15": a[a > 0],
    "c16": np.where(scores >= 70)[0],
    "c17": np.where(a < 0, 0, a),
    "c18": np.array([5, 3, 1]),
    "c19": N[[0, 2, 3], [2, 0, 1]],
    "c20": M + np.array([10, 20, 30, 40]),
    "c21": M * np.array([[1], [10], [100]]),
    "c22": N.mean(axis=0),
    "c23": grades.mean(axis=1),
    "c24": grades.max(axis=0),
    "c25": np.count_nonzero(tiny, axis=1),
    "c26": np.unique(labels),
    "c27": np.unique(labels, return_counts=True),
    "c28": np.sort(scores),
    "c29": scores[np.argsort(scores)[-3:]],
    "c30": M.T,
    "c31": X @ np.array([0.2, 0.3, 0.5]),
    "c32": X @ Y,
    "c33": np.linalg.norm(X, axis=1),
    "c34": X - X.mean(axis=0, keepdims=True),
    "c35": X / np.linalg.norm(X, axis=1, keepdims=True),
    "c36": (scores - scores.mean()) / scores.std(),
    "c37": np.concatenate([M, M], axis=0),
    "c38": np.concatenate([M, M], axis=1),
    "c39": np.stack([a, -a], axis=0),
    "c40": image[:, :, 0],
    "c41": image[1:3, 2:5, :],
    "c42": image.mean(axis=(0, 1)),
    "c43": np.cumsum(walk),
    "c44": np.diff(scores),
    "c45": np.clip(scores, 50, 90),
    "c46": np.pad(a, (2, 1), constant_values=0),
    "c47": np.eye(4, dtype=int),
    "c48": np.diag(np.array([1, 2, 3])),
    "c49": ((X[:, None, :] - X[None, :, :]) ** 2).sum(axis=2),
    "c50": np.einsum("ij,jk->ik", X, Y),
}


## Drill Ladder

Do not write loops unless a challenge explicitly asks for one. The point is to make array creation, slicing, broadcasting, and reductions automatic.


## Codex Review - NumPy Drill Results

Reviewed against the notebook's own `EXPECTED` answers and the wording of each prompt. I did not change your submitted `answer = ...` lines; the notes below each challenge preserve what you tried.

### Scorecard

| Category | Count | Challenges |
|---|---:|---|
| Correct by checker | 34/50 | c01-c12, c15, c17, c20-c24, c26-c27, c30-c32, c34, c37-c41, c43-c45, c47 |
| Correct but needs stricter/simpler habit | 3/50 | c03, c12, c47 |
| Wrong | 13/50 | c13, c14, c16, c18, c19, c25, c28, c29, c35, c36, c42, c46, c48 |
| Not attempted | 3/50 | c33, c49, c50 |
| Strict clean score | 31/50 | Checker-correct minus dtype/fragile-slice issues |

### What To Study Next

1. Slicing muscle memory: redo c13-c14 until `axis, start:stop:step` feels automatic.
2. Index-return vs value-return: redo c16, c18, c19, c29. The common mistake is returning the whole array, returning values when indices were requested, or returning indices when values were requested.
3. Axis reductions: redo c25 and c42. Before writing code, say the expected output shape out loud.
4. Normalization/standardization: redo c33, c35, c36. These are competition-useful preprocessing reflexes.
5. Shape-changing utilities: redo c46, c48, c49, c50. These expose whether you control padding, diagonal construction, broadcasting, and einsum notation.

### Retake Rule

For each wrong or missing challenge, first write the expected output shape as a comment, then write the one-line NumPy answer. Stop only when c13-c50 are all correct without reading these notes.



In [130]:
# Challenge 01 - creation (15 sec)
# Task: Create np.array([0, 1, 2, 3, 4]).
answer = np.array([0, 1, 2, 3,4])

check("c01", answer)


c01: correct


### Review Note - c01

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Your solution is already the direct solution.
- Reference answer:

```python
answer = np.array([0, 1, 2, 3, 4])
```

Focus tag: array creation.



In [131]:
# Challenge 02 - arange (15 sec)
# Task: Create the even numbers from 2 through 20.
answer = np.array(range(2, 22, 2))

check("c02", answer)


c02: correct


### Review Note - c02

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Simpler NumPy style: use `np.arange` instead of Python `range` wrapped in `np.array`.
- Reference answer:

```python
answer = np.arange(2, 21, 2)
```

Focus tag: arange.



In [132]:
# Challenge 03 - zeros and shape (15 sec)
# Task: Create a 2 by 3 integer array of zeros.
answer = np.zeros((2,3))

check("c03", answer)


c03: correct


### Review Note - c03

- Status: Accepted, but not strict
- As expected: The values are right, but the task asked for an integer array. `np.zeros((2, 3))` defaults to float.
- Simpler/cleaner route: Use the dtype argument when the prompt mentions integer.
- Reference answer:

```python
answer = np.zeros((2, 3), dtype=int)
```

Focus tag: shape and dtype.



In [133]:
# Challenge 04 - full (15 sec)
# Task: Create a 3 by 2 array filled with 7.
answer = np.full((3,2), 7)

check("c04", answer)


c04: correct


### Review Note - c04

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = np.full((3, 2), 7)
```

Focus tag: full arrays.



In [134]:
# Challenge 05 - linspace (20 sec)
# Task: Create 5 equally spaced values from 0 to 1.
answer = np.linspace(0, 1, 5)

check("c05", answer)


c05: correct


### Review Note - c05

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = np.linspace(0, 1, 5)
```

Focus tag: linspace.



In [135]:
# Challenge 06 - shape attributes (20 sec)
# Task: Return a tuple with M's shape, number of dimensions, and total size.
answer = M.shape, M.ndim, M.size

check("c06", answer)


c06: correct


### Review Note - c06

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct. Parentheses are optional here because commas create the tuple.
- Reference answer:

```python
answer = (M.shape, M.ndim, M.size)
```

Focus tag: shape attributes.



In [136]:
# Challenge 07 - astype (20 sec)
# Task: Convert a to floating point dtype.
answer = np.astype(a, np.float32)

check("c07", answer)


c07: correct


### Review Note - c07

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: More common object-method style: `a.astype(float)`.
- Reference answer:

```python
answer = a.astype(float)
```

Focus tag: dtype conversion.



In [137]:
# Challenge 08 - reshape (20 sec)
# Task: Reshape b into a 3 by 4 matrix.
answer = b.reshape(3, 4)

check("c08", answer)


c08: correct


### Review Note - c08

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = b.reshape(3, 4)
```

Focus tag: reshape.



In [138]:
# Challenge 09 - ravel (20 sec)
# Task: Flatten M into one dimension.
answer = M.flatten()

check("c09", answer)


c09: correct


### Review Note - c09

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: `M.ravel()` is slightly simpler and may avoid a copy; `flatten()` is also fine here.
- Reference answer:

```python
answer = M.ravel()
```

Focus tag: flattening.



In [139]:
# Challenge 10 - column indexing (20 sec)
# Task: Select the first column of M.
answer = M[:,0]

check("c10", answer)


c10: correct


### Review Note - c10

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = M[:, 0]
```

Focus tag: column indexing.



In [140]:
# Challenge 11 - negative indexing (20 sec)
# Task: Select the last row of M.
answer = M[-1]

check("c11", answer)


c11: correct


### Review Note - c11

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = M[-1]
```

Focus tag: negative indexing.



In [141]:
# Challenge 12 - 2D slicing (30 sec)
# Task: Select the first two rows and middle two columns of M.
answer = M[:2,M.shape[0]//2:(M.shape[0]//2)+2]

check("c12", answer)


c12: correct


### Review Note - c12

- Status: Correct, but fragile
- As expected: The output is right, but using `M.shape[0]` to choose columns is conceptually wrong. It only works here by coincidence because `3 // 2 == 1`.
- Simpler/cleaner route: Use explicit column slice `1:3`.
- Reference answer:

```python
answer = M[:2, 1:3]
```

Focus tag: 2D slicing.



In [142]:
# Challenge 13 - step slicing (30 sec)
# Task: Select every other column of M, starting from column 0.
answer = M[:,]

check("c13", answer)


c13: not yet
got: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
got shape: (3, 4)
expected shape: (3, 2)


### Review Note - c13

- Status: Wrong
- As expected: You returned all columns, not every other column.
- Simpler/cleaner route: Use a step in the column slice.
- Reference answer:

```python
answer = M[:, ::2]
```

Focus tag: step slicing.



In [143]:
# Challenge 14 - reverse slicing (30 sec)
# Task: Reverse the row order of M.
answer = M

check("c14", answer)


c14: not yet
got: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
got shape: (3, 4)
expected shape: (3, 4)


### Review Note - c14

- Status: Wrong
- As expected: You returned `M` unchanged, not reversed by rows.
- Simpler/cleaner route: Use a negative step on the row axis.
- Reference answer:

```python
answer = M[::-1]
```

Focus tag: reverse slicing.



In [144]:
# Challenge 15 - boolean mask (30 sec)
# Task: Return only the positive values in a.
answer = a[a>0]

check("c15", answer)


c15: correct


### Review Note - c15

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = a[a > 0]
```

Focus tag: boolean masks.



In [145]:
# Challenge 16 - np.where indices (40 sec)
# Task: Return the indices where scores are at least 70.
answer = np.where(a>=70, a, a)

check("c16", answer)


c16: not yet
got: [ 3 -1  0  7 -4  2]
got shape: (6,)
expected shape: (5,)


### Review Note - c16

- Status: Wrong
- As expected: You used array `a` and returned values. The task asks for indices in `scores` where the condition is true.
- Simpler/cleaner route: Use `np.where(condition)[0]` when you need indices.
- Reference answer:

```python
answer = np.where(scores >= 70)[0]
```

Focus tag: where indices.



In [146]:
# Challenge 17 - np.where values (40 sec)
# Task: Replace negative values in a with 0, preserving shape.
answer = np.where(a>0, a, 0)

check("c17", answer)


c17: correct


### Review Note - c17

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: A slightly closer wording is `np.where(a < 0, 0, a)`, but your condition is equivalent for this array because zeros stay zero.
- Reference answer:

```python
answer = np.where(a < 0, 0, a)
```

Focus tag: where values.



In [147]:
# Challenge 18 - fancy indexing (40 sec)
# Task: From a, select positions [3, 0, 1] in that order.
answer = a

check("c18", answer)


c18: not yet
got: [ 3 -1  0  7 -4  2]
got shape: (6,)
expected shape: (3,)


### Review Note - c18

- Status: Wrong
- As expected: You returned the whole array instead of selecting the requested positions.
- Simpler/cleaner route: Fancy indexing takes a list/array of positions.
- Reference answer:

```python
answer = a[[3, 0, 1]]
```

Focus tag: fancy indexing.



In [148]:
# Challenge 19 - paired fancy indexing (45 sec)
# Task: From N, select values at (row, col): (0,2), (2,0), (3,1).
answer = N

check("c19", answer)


c19: not yet
got: [[ 2 -1  5]
 [ 0  3 -2]
 [ 4  4  1]
 [-3  2  6]]
got shape: (4, 3)
expected shape: (3,)


### Review Note - c19

- Status: Wrong
- As expected: You returned the whole matrix instead of paired row/column selections.
- Simpler/cleaner route: Use one index array for rows and one for columns.
- Reference answer:

```python
answer = N[[0, 2, 3], [2, 0, 1]]
```

Focus tag: paired fancy indexing.



In [149]:
# Challenge 20 - broadcast row vector (45 sec)
# Task: Add [10, 20, 30, 40] to every row of M.
answer = M + np.array([10, 20, 30, 40])

check("c20", answer)


c20: correct


### Review Note - c20

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = M + np.array([10, 20, 30, 40])
```

Focus tag: row broadcasting.



In [150]:
# Challenge 21 - broadcast column vector (45 sec)
# Task: Multiply M's rows by 1, 10, and 100 respectively.
answer = M * np.array((1, 10, 100)).reshape(-1,1)

check("c21", answer)


c21: correct


### Review Note - c21

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Your reshape is good. Equivalent explicit column vector: `np.array([[1], [10], [100]])`.
- Reference answer:

```python
answer = M * np.array([1, 10, 100]).reshape(-1, 1)
```

Focus tag: column broadcasting.



In [151]:
# Challenge 22 - axis 0 reduction (45 sec)
# Task: Compute the mean of each column in N.
answer = N.mean(axis=0)

check("c22", answer)


c22: correct


### Review Note - c22

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = N.mean(axis=0)
```

Focus tag: axis 0 reductions.



In [152]:
# Challenge 23 - axis 1 reduction (45 sec)
# Task: Compute the mean grade for each student.
answer = grades.mean(axis=1)

check("c23", answer)


c23: correct


### Review Note - c23

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = grades.mean(axis=1)
```

Focus tag: axis 1 reductions.



In [153]:
# Challenge 24 - max by column (45 sec)
# Task: Compute the best score for each exam/column in grades.
answer = grades.max(axis=0)

check("c24", answer)


c24: correct


### Review Note - c24

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = grades.max(axis=0)
```

Focus tag: column reductions.



In [154]:
# Challenge 25 - count_nonzero (45 sec)
# Task: Count nonzero entries in each row of tiny.
answer = tiny[tiny!=0].shape

check("c25", answer)


c25: not yet
got: (5,)
expected shape: (3,)


### Review Note - c25

- Status: Wrong
- As expected: You counted all nonzero values and returned the shape of the filtered 1D result. The task asks for one count per row.
- Simpler/cleaner route: Use the `axis` argument directly.
- Reference answer:

```python
answer = np.count_nonzero(tiny, axis=1)
```

Focus tag: counting with axis.



In [155]:
# Challenge 26 - unique (45 sec)
# Task: Return the unique labels.
answer = np.unique(labels)

check("c26", answer)


c26: correct


### Review Note - c26

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = np.unique(labels)
```

Focus tag: unique values.



In [156]:
# Challenge 27 - unique counts (60 sec)
# Task: Return unique labels and their counts.
answer = np.unique_counts(labels)

check("c27", answer)


c27: correct


### Review Note - c27

- Status: Correct
- As expected: Yes in your environment.
- Simpler/cleaner route: More portable/common: `np.unique(labels, return_counts=True)`. `np.unique_counts` is less familiar and may not exist in older NumPy versions.
- Reference answer:

```python
answer = np.unique(labels, return_counts=True)
```

Focus tag: unique counts.



In [157]:
# Challenge 28 - sort (45 sec)
# Task: Return sorted scores in ascending order.
answer = scores

check("c28", answer)


c28: not yet
got: [ 55  72  91  48  88  64  79  35 100  67]
got shape: (10,)
expected shape: (10,)


### Review Note - c28

- Status: Wrong
- As expected: You returned unsorted `scores`.
- Simpler/cleaner route: Use `np.sort`.
- Reference answer:

```python
answer = np.sort(scores)
```

Focus tag: sorting.



In [158]:
# Challenge 29 - argsort (60 sec)
# Task: Return the top 3 scores using argsort. Ascending order is fine.
answer = scores.argsort()[:3]

check("c29", answer)


c29: not yet
got: [7 3 0]
got shape: (3,)
expected shape: (3,)


### Review Note - c29

- Status: Wrong
- As expected: You returned indices of the three smallest scores. The task asks for the top 3 score values.
- Simpler/cleaner route: Use the last three sorted indices, then index `scores`.
- Reference answer:

```python
answer = scores[np.argsort(scores)[-3:]]
```

Focus tag: argsort.



In [159]:
# Challenge 30 - transpose (30 sec)
# Task: Transpose M.
answer = M.T

check("c30", answer)


c30: correct


### Review Note - c30

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = M.T
```

Focus tag: transpose.



In [160]:
# Challenge 31 - matrix vector (60 sec)
# Task: Compute a weighted sum of X columns with weights [0.2, 0.3, 0.5].
answer = X @ np.array((0.2, 0.3, 0.5))

check("c31", answer)


c31: correct


### Review Note - c31

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = X @ np.array([0.2, 0.3, 0.5])
```

Focus tag: matrix-vector product.



In [161]:
# Challenge 32 - matrix matrix (60 sec)
# Task: Compute the matrix product X @ Y.
answer = X @ Y

check("c32", answer)


c32: correct


### Review Note - c32

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = X @ Y
```

Focus tag: matrix-matrix product.



In [162]:
# Challenge 33 - row norm (60 sec)
# Task: Compute the L2 norm of each row in X.
answer = None

check("c33", answer)


c33: not solved yet


### Review Note - c33

- Status: Not attempted
- As expected: No answer was provided.
- Simpler/cleaner route: Use `np.linalg.norm` over columns within each row, so `axis=1`.
- Reference answer:

```python
answer = np.linalg.norm(X, axis=1)
```

Focus tag: row norms.



In [163]:
# Challenge 34 - keepdims broadcasting (75 sec)
# Task: Column-center X by subtracting each column mean.
answer = X - X.mean(axis=0)

check("c34", answer)


c34: correct


### Review Note - c34

- Status: Correct
- As expected: Yes. The checker accepts the shape `(4, 3)`.
- Simpler/cleaner route: For a reusable broadcasting habit, keep the mean as `(1, 3)` with `keepdims=True`.
- Reference answer:

```python
answer = X - X.mean(axis=0, keepdims=True)
```

Focus tag: centering and broadcasting.



In [164]:
# Challenge 35 - row normalization (75 sec)
# Task: Normalize each row of X to unit length.
answer = X

check("c35", answer)


c35: not yet
got: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [2. 4. 8.]]
got shape: (4, 3)
expected shape: (4, 3)


### Review Note - c35

- Status: Wrong
- As expected: You returned `X` unchanged.
- Simpler/cleaner route: Compute row norms with `keepdims=True`, then divide.
- Reference answer:

```python
answer = X / np.linalg.norm(X, axis=1, keepdims=True)
```

Focus tag: row normalization.



In [165]:
# Challenge 36 - standardization (75 sec)
# Task: Standardize scores to mean 0 and standard deviation 1.
answer = scores.std()

check("c36", answer)


c36: not yet
got: 19.31035991378721
expected shape: (10,)


### Review Note - c36

- Status: Wrong
- As expected: You returned only the standard deviation scalar. Standardization needs one transformed value per score.
- Simpler/cleaner route: Subtract the mean, then divide by the standard deviation.
- Reference answer:

```python
answer = (scores - scores.mean()) / scores.std()
```

Focus tag: standardization.



In [166]:
# Challenge 37 - concatenate rows (60 sec)
# Task: Stack M under itself to make a 6 by 4 array.
answer = np.vstack((M, M))

check("c37", answer)


c37: correct


### Review Note - c37

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: `np.concatenate([M, M], axis=0)` is the general version; `vstack` is fine.
- Reference answer:

```python
answer = np.vstack((M, M))
```

Focus tag: row concatenation.



In [167]:
# Challenge 38 - concatenate columns (60 sec)
# Task: Place M next to itself to make a 3 by 8 array.
answer = np.hstack((M,M))

check("c38", answer)


c38: correct


### Review Note - c38

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: `np.concatenate([M, M], axis=1)` is the general version; `hstack` is fine.
- Reference answer:

```python
answer = np.hstack((M, M))
```

Focus tag: column concatenation.



In [168]:
# Challenge 39 - stack new axis (60 sec)
# Task: Stack a and -a into a 2 by 6 array.
answer = np.vstack((a,-a))

check("c39", answer)


c39: correct


### Review Note - c39

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: `np.stack([a, -a], axis=0)` states the new-axis intent most clearly; `vstack` also works here.
- Reference answer:

```python
answer = np.stack([a, -a], axis=0)
```

Focus tag: stacking.



In [169]:
# Challenge 40 - 3D indexing (60 sec)
# Task: Select channel 0 from image.
answer = image[:,:,0]

check("c40", answer)


c40: correct


### Review Note - c40

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = image[:, :, 0]
```

Focus tag: 3D indexing.



In [170]:
# Challenge 41 - 3D slicing (75 sec)
# Task: Crop rows 1:3 and columns 2:5 from image, keeping all channels.
answer = image[1:3,2:5]

check("c41", answer)


c41: correct


### Review Note - c41

- Status: Correct
- As expected: Yes. Omitting the final `:` is okay because NumPy keeps the remaining channel axis.
- Simpler/cleaner route: For clarity in image code, write all axes: `image[1:3, 2:5, :]`.
- Reference answer:

```python
answer = image[1:3, 2:5, :]
```

Focus tag: 3D slicing.



In [171]:
# Challenge 42 - multi-axis reduction (75 sec)
# Task: Compute the mean value per image channel.
answer = image.mean(axis=2)

check("c42", answer)


c42: not yet
got: [[ 1.  4.  7. 10. 13.]
 [16. 19. 22. 25. 28.]
 [31. 34. 37. 40. 43.]
 [46. 49. 52. 55. 58.]]
got shape: (4, 5)
expected shape: (3,)


### Review Note - c42

- Status: Wrong
- As expected: You averaged across channels for each pixel. The task asks for one mean per channel, so average over row and column axes.
- Simpler/cleaner route: Reduce axes `(0, 1)`.
- Reference answer:

```python
answer = image.mean(axis=(0, 1))
```

Focus tag: multi-axis reductions.



In [172]:
# Challenge 43 - cumsum (60 sec)
# Task: Compute the cumulative position after each step in walk.
answer = np.cumsum(walk)

check("c43", answer)


c43: correct


### Review Note - c43

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = np.cumsum(walk)
```

Focus tag: cumulative sums.



In [173]:
# Challenge 44 - diff (60 sec)
# Task: Compute consecutive score differences.
answer = np.diff(scores)

check("c44", answer)


c44: correct


### Review Note - c44

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: Already direct.
- Reference answer:

```python
answer = np.diff(scores)
```

Focus tag: differences.



In [174]:
# Challenge 45 - clip (60 sec)
# Task: Clip scores so every value is between 50 and 90.
answer = scores.clip(50, 90)

check("c45", answer)


c45: correct


### Review Note - c45

- Status: Correct
- As expected: Yes.
- Simpler/cleaner route: `np.clip(scores, 50, 90)` is the function form; `scores.clip(50, 90)` is fine.
- Reference answer:

```python
answer = np.clip(scores, 50, 90)
```

Focus tag: clipping.



In [175]:
# Challenge 46 - pad (75 sec)
# Task: Pad a with two zeros on the left and one zero on the right.
answer = np.pad(a, 2)

check("c46", answer)


c46: not yet
got: [ 0  0  3 -1  0  7 -4  2  0  0]
got shape: (10,)
expected shape: (9,)


### Review Note - c46

- Status: Wrong
- As expected: `np.pad(a, 2)` pads two values on both sides. The task asks for two on the left and one on the right.
- Simpler/cleaner route: Pass a pair for the before/after padding width.
- Reference answer:

```python
answer = np.pad(a, (2, 1), constant_values=0)
```

Focus tag: padding.



In [176]:
# Challenge 47 - eye (45 sec)
# Task: Create a 4 by 4 integer identity matrix.
answer = np.identity(4)

check("c47", answer)


c47: correct


### Review Note - c47

- Status: Correct, but not strict
- As expected: The values are right, but the task asked for an integer identity matrix. `np.identity(4)` defaults to float.
- Simpler/cleaner route: Use `np.eye` with `dtype=int`.
- Reference answer:

```python
answer = np.eye(4, dtype=int)
```

Focus tag: identity matrices.



In [177]:
# Challenge 48 - diag (60 sec)
# Task: Create a diagonal matrix with diagonal [1, 2, 3].
answer = np.eye(3)

check("c48", answer)


c48: not yet
got: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
got shape: (3, 3)
expected shape: (3, 3)


### Review Note - c48

- Status: Wrong
- As expected: You created an identity matrix with diagonal all ones. The requested diagonal is `[1, 2, 3]`.
- Simpler/cleaner route: Use `np.diag` when the diagonal values are given.
- Reference answer:

```python
answer = np.diag([1, 2, 3])
```

Focus tag: diagonal matrices.



In [178]:
# Challenge 49 - broadcast pairwise distances (3 min)
# Task: Compute the full pairwise squared-distance matrix between rows of X.
answer = None

check("c49", answer)


c49: not solved yet


### Review Note - c49

- Status: Not attempted
- As expected: No answer was provided.
- Simpler/cleaner route: Create row-pair differences with broadcasting, square them, then sum over features.
- Reference answer:

```python
answer = ((X[:, None, :] - X[None, :, :]) ** 2).sum(axis=2)
```

Focus tag: broadcast pairwise distances.



In [179]:
# Challenge 50 - einsum (3 min)
# Task: Recreate X @ Y using np.einsum.
answer = None

check("c50", answer)


c50: not solved yet


### Review Note - c50

- Status: Not attempted
- As expected: No answer was provided.
- Simpler/cleaner route: Use index labels for rows/features/output columns.
- Reference answer:

```python
answer = np.einsum("ij,jk->ik", X, Y)
```

Focus tag: einsum.



## Stop Condition

You are done when:
- Challenges 01-20 feel automatic.
- For 21-40, you can predict the output shape before running the cell.
- For 41-50, you can debug a wrong answer by printing only shapes first.

Reusable contest reflex: shape first, values second.
