In [48]:
import numpy as np
import pandas as pd
import random

In [49]:
np.random.seed = 42
random.seed(42)

In [50]:
# Solution of problem 1:
random = np.random.randn(12,5)
print(random)

[[ 0.91716466 -0.13936601  0.47214241 -0.25520715 -0.05389588]
 [-0.31704067 -0.17863437  0.01238867  0.16699057  0.37962847]
 [-1.51843601 -0.62438478 -1.13814523 -0.51523944 -1.40493924]
 [ 0.46517898  1.01403649 -1.33188165 -0.45352778  1.22289298]
 [-0.27179488  1.10270637 -1.58079663 -0.20980493  0.84956476]
 [-2.50155801 -0.08669714  0.29008332 -1.98649399  0.12618934]
 [-0.17464009 -0.95642162  2.01027914  0.06732912 -0.86372142]
 [-0.50212606 -0.27818511 -0.60072239  0.50132589 -1.64492085]
 [-0.7628433   0.20267687  0.65038782 -1.61445573  0.3088957 ]
 [ 1.55175326 -0.12178001  0.84110365 -0.93686224 -0.0824487 ]
 [-0.12298038  1.4012052   0.40803605 -0.33620295  0.42258733]
 [ 0.06384485 -1.4855393   1.09366516 -1.05657418 -0.18881838]]
